apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-world
  labels:
    app: k8s-hello-world
spec:
  replicas: 4
  template:
    metadata:
      name: k8s-hello-world
      labels:
        app: k8s-hello-world
    spec:
      containers:
        - name: k8s-hello-world
          image: rattus1perfectus/k8s-hello-world:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
      restartPolicy: Always
  selector:
    matchLabels:
      app: k8s-hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-world
spec:
  selector:
    app: k8s-hello-world
  ports:
    - port: 5001
      targetPort: 5000
  type: LoadBalancer